azbuduvelikej@gmail.com is requesting the role roles/run.developer on the resource excellent-booking-rv7sv.

Requestor’s message:
"Google Ai Cloud run"

Click the following link to investigate and remediate this request for azbuduvelikej@gmail.com:

console.cloud.google.com/iam-admin/troubleshooter/summary;permissions=run.services.create;token=ATRLMDo5D6TzbsZwtxG5LtnjEDUUOou6qUQKZvGgx3UTAJSU7Xp8I1svAHdEDH9ETH4WH9wU6V1AGPRz08a5UoBQKEWBfBhtlAGh_ffwHgCevRz2daWcYFrPBJP7LvNuTiuG_cAkvIUhbTq7tFlU0hJTPbcvOJRDFcza0EF9T9nyg7AxRnCcrlBjXdJM-qZO?utm_campaign=role_request&utm_source=cloud_console
